apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-teste-1
  namespace: fiap-pos-tech
  region: us-east-1

vpc:
  cidr: "172.31.0.0/16"
  subnets:
    public:
      us-east-1a:
        id: subnet-0b17c6144cbf7657c
      us-east-1b:
        id: subnet-0a39c9b965507d8c3
      us-east-1c:
        id: subnet-022e1e3e547c879a9
      us-east-1d:
        id: subnet-09446d9fe4aa646e7
      us-east-1f:
        id: subnet-07195684c8ac083ad

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        autoScaler: true
        albIngress: true
